SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Table2] (
		[col1]     [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[col2]     [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [dbo].[Table2] SET (LOCK_ESCALATION = TABLE)
GO
